name: Bug Report
description: Help us fix this issue by providing details about the problem.
title: "[Bug]: "
labels:
  - bug
assignees: [ ]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for reporting this issue! 
        Please provide the details below so we can investigate and fix it.

  - type: input
    id: summary
    attributes:
      label: Short Description
      description: Provide a short summary of the bug.
      placeholder: "Example: Bot stops sending notifications after schedule update"
    validations:
      required: true

  - type: textarea
    id: steps_to_reproduce
    attributes:
      label: STR (Steps to Reproduce)
      description: Describe the steps to reproduce the behavior.
      placeholder: |
        1. ...
        2. ...
        3. ...
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: EXR (Expected Result)
      description: What did you expect to happen?
      placeholder: "Example: Bot should send a message to the Telegram channel."
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: ACR (Actual Result)
      description: What actually happened?
      placeholder: "Example: Bot logs schedule changes but does not send notifications."
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Screenshots / Logs
      description: If possible, attach screenshots, logs, or console output.
      placeholder: "Paste logs here or upload screenshots."
      render: bash
    validations:
      required: false

  - type: dropdown
    id: environment_os
    attributes:
      label: Operating System
      description: Which OS are you using?
      options:
        - Linux
        - macOS
        - Windows
        - Other
    validations:
      required: true

  - type: input
    id: python_version
    attributes:
      label: Python Version
      placeholder: "Example: 3.11.7"
    validations:
      required: true

  - type: input
    id: app_version
    attributes:
      label: Application Version
      placeholder: "Example: v1.0.0"
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Information
      description: Any extra context or information.
      placeholder: "Anything that might help..."
    validations:
      required: false